### ISSUE TITLE
Bug：未对次主力连续合约88A2做单独处理，导致郑商所和部分大商所查找不到相应标的

### ISSUE THREAD

**Issue by Song-Joey** [vnpy/vnpy_rqdata#16]

**Comment by vnpy** [comment]
请附上报错截图？

**Comment by Song-Joey** [comment]
![1](https://github.com/vnpy/vnpy_rqdata/assets/114914920/f21e61d5-c43d-45e1-9f55-18504c4476d4)
![2](https://github.com/vnpy/vnpy_rqdata/assets/114914920/184f342b-f723-47d5-83c1-105435bcb52a)

**Comment by noranhe** [comment]
建议更新一下vnpy_rqdata之后再试吧，vnpy_rqdata2.11.11.4就已经提供次主力支持了
