### ISSUE TITLE
郑商所下载数据rq_symbol处理

### ISSUE THREAD

**Issue by duoshaga** [vnpy/vnpy_rqdata#9]
https://github.com/vnpy/vnpy_rqdata/blob/main/vnpy_rqdata/rqdata_datafeed.py#L67-L72
这么处理填写合约代码时必须少填一位数，比如SA2301就得填SA301。询问下为啥要这么处理？

**Comment by vnpy** [comment]
这是交易所规则，郑商所的合约代码就是：英文大写+数字3位

VeighNa统一采用了各家交易所自身的代码命名规则。

**Comment by duoshaga** [comment]
好的，感谢。
